[mypy]
files = source, test

mypy_path = source

python_version = 3.12
show_error_codes = True
ignore_missing_imports = True

warn_redundant_casts = True
warn_unused_ignores = True

disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
warn_return_any = True
